import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import Link from "next/link";
import Navigation from "@/components/Navigation";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-roboto",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Bazar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ ...roboto.style, backgroundColor: "white" }}>
        <Navigation />
        <main className={roboto.className} style={{ ...roboto.style, backgroundColor: "white", margin: "25px" }}>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
